@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mythscapes.common.entities.projectile;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;