@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mythscapes.client.renderers.entities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;