@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mythscapes.datagen.loot_table_providers;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;