@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.radish.mythscapes.datagen.loot_table_providers;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;