@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mythscapes.client.particles;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;